default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USER'] || 'postgres'%>
  password: <%= ENV['PG_PASS'] || 'password'%>
  host: <%= ENV['PG_HOST'] || '127.0.0.1' %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'mailer_app_development'%>

test:
  <<: *default
  database: mailer_app_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'mailer_app_production'%>